# Markdownlint Configuration
# Source: https://github.com/DavidAnson/markdownlint
# Schema: https://raw.githubusercontent.com/DavidAnson/markdownlint/main/schema/markdownlint-config-schema.json

# Enable all rules by default
default: true

# Extend another configuration file (if needed)
# extends: null

# Rule Configurations
# Set to false to disable a rule, or configure with specific options

# MD001 - Heading levels should only increment by one level at a time
MD001: true

# MD003 - Heading style (consistent, atx, atx_closed, setext, setext_with_atx, setext_with_atx_closed)
MD003:
  style: "consistent"

# MD004 - Unordered list style (consistent, asterisk, plus, dash, sublist)
MD004:
  style: "consistent"

# MD005 - Inconsistent indentation for list items at the same level
MD005: true

# MD007 - Unordered list indentation
MD007:
  indent: 2
  start_indented: false
  start_indent: 2

# MD009 - Trailing spaces
MD009:
  br_spaces: 2
  list_item_empty_lines: false
  strict: false

# MD010 - Hard tabs
MD010:
  code_blocks: true
  ignore_code_languages: []
  spaces_per_tab: 1

# MD011 - Reversed link syntax
MD011: true

# MD012 - Multiple consecutive blank lines
MD012:
  maximum: 1

# MD013 - Line length
MD013:
  line_length: 80
  heading_line_length: 80
  code_block_line_length: 80
  code_blocks: true
  tables: true
  headings: true
  strict: false
  stern: false

# MD014 - Dollar signs used before commands without showing output
MD014: true

# MD018 - No space after hash on atx style heading
MD018: true

# MD019 - Multiple spaces after hash on atx style heading
MD019: true

# MD020 - No space inside hashes on closed atx style heading
MD020: true

# MD021 - Multiple spaces inside hashes on closed atx style heading
MD021: true

# MD022 - Headings should be surrounded by blank lines
MD022:
  lines_above: 1
  lines_below: 1

# MD023 - Headings must start at the beginning of the line
MD023: true

# MD024 - Multiple headings with the same content
MD024:
  siblings_only: false

# MD025 - Multiple top-level headings in the same document
MD025:
  level: 1

# MD026 - Trailing punctuation in heading
MD026:
  punctuation: ".,;:!。，；：！"

# MD027 - Multiple spaces after blockquote symbol
MD027: true

# MD028 - Blank line inside blockquote
MD028: true

# MD029 - Ordered list item prefix (one, ordered, one_or_ordered, zero)
MD029:
  style: "one_or_ordered"

# MD030 - Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# MD031 - Fenced code blocks should be surrounded by blank lines
MD031:
  list_items: true

# MD032 - Lists should be surrounded by blank lines
MD032: true

# MD033 - Inline HTML
MD033:
  allowed_elements: []

# MD034 - Bare URL used
MD034: true

# MD035 - Horizontal rule style (consistent, or specific style)
MD035:
  style: "consistent"

# MD036 - Emphasis used instead of a heading
MD036:
  punctuation: ".,;:!?。，；：！？"

# MD037 - Spaces inside emphasis markers
MD037: true

# MD038 - Spaces inside code span elements
MD038: true

# MD039 - Spaces inside link text
MD039: true

# MD040 - Fenced code blocks should have a language specified
MD040:
  allowed_languages: []
  language_only: false

# MD041 - First line in a file should be a top-level heading
MD041:
  level: 1
  front_matter_title: ""

# MD042 - No empty links
MD042: true

# MD043 - Required heading structure
MD043:
  headings: []
  match_case: false

# MD044 - Proper names should have the correct capitalization
MD044:
  names: []
  code_blocks: true
  html_elements: true

# MD045 - Images should have alternate text (alt text)
MD045: true

# MD046 - Code block style (consistent, fenced, indented)
MD046:
  style: "consistent"

# MD047 - Files should end with a single newline character
MD047: true

# MD048 - Code fence style (consistent, backtick, tilde)
MD048:
  style: "consistent"

# MD049 - Emphasis style (consistent, asterisk, underscore)
MD049:
  style: "consistent"

# MD050 - Strong style (consistent, asterisk, underscore)
MD050:
  style: "consistent"

# MD051 - Link fragments should be valid
MD051: true

# MD052 - Reference links and images should use a label that is defined
MD052:
  shortcut_syntax: false

# MD053 - Link and image reference definitions should be needed
MD053:
  ignored_definitions: ["//"]

# MD054 - Link and image style
MD054:
  autolink: true
  inline: true
  full: true
  collapsed: true
  shortcut: true
  url_inline: true

# MD055 - Table pipe style (consistent, leading_only, trailing_only, leading_and_trailing, no_leading_or_trailing)
MD055:
  style: "consistent"

# MD056 - Table column count
MD056: true

# MD058 - Tables should be surrounded by blank lines
MD058: true

# MD059 - Link text should be descriptive
MD059:
  prohibited_texts:
    - "click here"
    - "here"
    - "link"
    - "more"
