moniker: "repo-config"
name: "Repository Configuration"
type: "config"
description: "Root-level repository configuration files including package management, build tools, and git settings"
root: ""
root_type: "config-files"

versioning:
  version_scheme: "MAJOR.MINOR.PATCH"
  changelog_path: "CHANGELOG.md"

source:
  includes:
    - "*.json"
    - "*.yml"
    - "*.yaml"
    - ".gitignore"
    - ".gitattributes"
    - "LICENSE"
    - "*.lock"

depends_on: []
