// Code generated by go:generate. DO NOT EDIT.
// Generated by: go run tools/gen-registry.go

package main

// funcRegistry maps function names to actual functions
// This is auto-generated from command files
var funcRegistry = map[string]CommandFunc{
}
