# Version: 0.1.0

moniker: "requirements"
name: "The requirements of the repository"
type: "requirements"
description: "Repository specific requirements"

source:
  changelog_path: "specs/CHANGELOG.md"
  root: "requirements"

depends_on: []
